version: '2'
services:
    nginx_server2:
        image: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ~/:/usr/share/nginx/html
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./ssl/hshen.crt:/etc/nginx/hshen.crt
            - ./ssl/hshen.key:/etc/nginx/hshen.key
